# Data Science Numpy & CSV's

## Tasks Today:

1) <b>Numpy</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Python List Comparison <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) In-Class Exercise #1 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Creating an NDArray <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.array() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.zeros() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.ones() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.arange() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Making Lists into NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Performing Calculations on NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Summation <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Difference <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) Numpy Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Multi-dimensional Arrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Indexing NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Checking NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Altering NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; k) Checking the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; l) Altering the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; m) In-Class Exercise #2 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; n) Complex Indexing & Assigning <br>
 &nbsp;&nbsp;&nbsp;&nbsp; o) Elementwise Multplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp; p) np.where() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; q) Random Sampling <br>

2) <b>Working With CSV's</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Imports <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Reading a CSV <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Loading a CSV's Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Checking Number of Records <br>
 
3) <b>Exercises</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) #1 - Calculate BMI with NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) #2 - Find the Average Sum of Marathon Runners <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) #3 - Random Matrix Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) #4 - Comparing Boston Red Sox Hitting Numbers <br>

## Numpy <br>

<p>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.</p>
<ul>
    <li>Shape = Rows & Columns</li>
    <li>Matrix = Entire Array</li>
    <li>Vector = Variables to be applied (same vector as the one used in physics)</li>
    <li>Array = Similar to lists</li>
</ul>

#### Python List Comparison

<p>Lists are flexible, dynamic python objects that do their job quite well. But they do not support some mathematical operations in an intuitive way. Consider the summation of two lists, $l_1$ and $l_2$</p>

In [3]:
# create two lists and sum both of them together (results may not be what you expect)
l_1 = [1,2,3]
l_2 = [4,5,6]

print(l_1 + l_2)
print(l_1 - l_2)

[1, 2, 3, 4, 5, 6]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

<p>If we wanted to sum lists elementwise, we could write our own function that does the job entirely within the framework of python</p>

#### In-Class Exercise #1 - Write a function that sums the indexes of two lists <br>
<p>Ex: [2, 3, 4] + [1, 5, 2] = [3, 8, 6]</p>

In [4]:
def add(list1,list2):
    final = []
    for i in range(len(list1)):
        a = list1[i] + list2[i]
        final.append(a)
    return final

add([2, 3, 4],[1, 5, 2])

[3, 8, 6]

#### Importing

In [5]:
# always import as np, standard across all of data science
!pip install numpy
import numpy as np

#### Creating an NDArray <br>
<p>NumPy is based around a class called the $\textit{NDArray}$, which is a flexible vector / matrix class that implements the intuitive matrix and vector arithmatic lacking in basic Python. Let's start by creating some NDArrays:</p>

###### - np.array()

In [6]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

###### - np.zeros()

In [7]:
# Shape -- np.zeros() has a parameter of "shape" that must be given
arr_zeros = np.zeros((3,3))
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

###### - np.ones()

In [11]:
arr_ones = np.ones((3,3), int)
arr_ones

# notice no dots after the numbers, because we specified the datatype to be integer

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

###### - np.arange()

In [12]:
arr_range = np.arange(1,12)
arr_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

###### - Making Lists into NDArrays

In [13]:
l_1 = [4,5,6]

arr_list = np.array(l_1)
arr_list

array([4, 5, 6])

#### Performing Calculations on NDArrays

###### - Summation

In [22]:
arr_list1 = np.array([5,10,15,20,25])
arr_list2 = np.array([10,20,30,40,50])

def add(list1,list2):
    final = []
    for i in range(len(list1)):
        a = list1[i] + list2[i]
        final.append(a)
    return final

print(add(arr_list1,arr_list2))

result_sum = arr_list1 + arr_list2
print(result_sum)

[15, 30, 45, 60, 75]
[15 30 45 60 75]


###### - Difference

In [16]:
result_diff = abs(arr_list1 - arr_list2)
result_diff

array([ 5, 10, 15, 20, 25])

###### - Multiplication

In [17]:
result_mul = arr_list1 * arr_list2
result_mul

array([  50,  200,  450,  800, 1250])

###### - Division

In [18]:
result_diff = arr_list2 / arr_list1
result_diff

array([2., 2., 2., 2., 2.])

In [19]:
# Modulo
result_mod = arr_list2 % arr_list1
result_mod


array([0, 0, 0, 0, 0], dtype=int32)

In [20]:
# Floor Division
result_floor = arr_list2 // arr_list1
result_floor

array([2, 2, 2, 2, 2], dtype=int32)

#### Numpy Subsetting

In [26]:
# result3 <= 800
print(result_mul <= 800)
print(result_mul[result_mul <= 800])

# test_ndStrings = np.array(['Bob','Mark','Angelica','Barb'])
# print(test_ndStrings[test_ndStrings[0] == 'B'])

# conditioal check, returns true or false
# print(arr1 < 2)
# print(arr2 >= 2)

# conditional check, that returns the elements that meet the given condition


[ True  True  True  True False]
[ 50 200 450 800]


#### Multi-dimensional Arrays <br>
<p>NumPy seamlessly supports multidimensional arrays and matrices of arbitrary dimension without nesting NDArrays. NDArrays themselves are flexible and extensible and may be defined with such dimensions, with a rich API of common functions to facilitate their use. Let's start by building a two dimensional 3x3 matrix by conversion from a nested group of core python lists $M = [l_0, l_1, l_2]$:</p>

In [31]:
aList = [0,1,2]
bList = [3,4,5]
cList = [6,7,8]

# first step: convert lists into a Matrix
M = [aList,bList,cList]
print(M)

# second step: place Matrix inside NDArray
ND_M = np.array(M)
print(ND_M)


[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Indexing NDArrays <br>
<p> Similar to lists within lists; however, the syntax looks more like C programming language.... It is [1, 2] to access the second row, third element.</p>

In [32]:
print(f'Getting the Middle element within the Matrix: {ND_M[1,1]}')

Getting the Middle element within the Matrix: 4


#### Assigning Values in NDArrays

In [33]:
  # trying to change to floating point number
ND_M[1,1] = 9.5
ND_M

array([[0, 1, 2],
       [3, 9, 5],
       [6, 7, 8]])

<p>Notice above how we ended up with a 1 in the target element's place. This is a data type issue. The .dtype() method is supported by all NDArrays, as well as the .astype() method for casting between data types:</p>

#### Checking NDArray Type

In [34]:
# usind the .dtype() method
nd_type = ND_M.dtype
nd_type

dtype('int32')

#### Altering NDArray Type

In [35]:
result_type = nd_type
print(f'Type before change: {result_type}')

# Change happens here...
changed = ND_M.astype(np.float64)

result_changed = changed

print(f'Type after change: {result_changed.dtype} ')
print(changed)

Type before change: int32
Type after change: float64 
[[0. 1. 2.]
 [3. 9. 5.]
 [6. 7. 8.]]


In [36]:
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape
numpy_shape = ND_M.shape
print(numpy_shape)
print(type(numpy_shape))

(3, 3)
<class 'tuple'>


#### Checking the Shape <br>
<p>The behavior and properties of an NDArray are often sensitively dependent on the $\textit{shape}$ of the NDArray itself. The shape of an array can be found by calling the .shape method, which will return a tuple containing the array's dimensions:</p>

In [37]:
 # shape is always rows x columns
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape
numpy_shape = ND_M.shape
print(numpy_shape)
print(type(numpy_shape))

(3, 3)
<class 'tuple'>


#### Altering the Shape <br>
<p>As long as the number of elements remains fixed, we can reshape NDArrays at will:</p>

In [38]:
# Change the shape of the numpy array
# Using the method .reshape()

# The reshape should be a multiple of the original shape
# Meaning we can have a shape of (1,9) or (9,1) or (3,3)

# (9,1) == 9 rows , 1 column

print(ND_M.reshape((9,1)))


[[0]
 [1]
 [2]
 [3]
 [9]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
# keep in mind that the shape numbers do matter, (9, 1) is different than (1, 9)


#### In-Class Exercise #2 - Create a matrix of range 0 up to 16 and reshape it into a 4x4 matrice

In [41]:
# arr1 = np.array([0,16])
# new_array = np.arr1([4,4])
# print(type(test.shape))

arr_1 = np.arange(0,16)
print(arr_1)
reshaped = arr_1.reshape((4,4))
print(reshaped)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### Complex Indexing & Assinging

In [44]:
M_zeros = np.zeros((6,6))
print('Resetting Matrix')
print('Before Assignment:')
print(M_zeros)

# set every first element in each row to 1
M_zeros[:,0] = 1
print('\n After Assigning 1 to First Column:')
print(M_zeros)

# Set every element in the axis of 3 to 5 (Excluding 5) to be equal to 5
M_zeros[2:5, :] = 5
print('\n After Assigning 5 to rows 3-5 (not including 5)')
print(M_zeros)

Resetting Matrix
Before Assignment:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

 After Assigning 1 to First Column:
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]

 After Assigning 5 to rows 3-5 (not including 5)
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [1. 0. 0. 0. 0. 0.]]


#### Elementwise Multiplication

<p>As long as the shapes of NDArrays are 'compatible', they can be multiplied elementwise, broadcasted, used in inner products, and much much more. 'Compatible' in this context can mean compatible in the linear algebraic sense, i.e. for inner products and other matrix multiplication, or simply sharing a dimension in such a manner that broadcasting 'makes sense'. Here are some examples of this:</p>

In [45]:
# Initialize a vector of range 6, reset to zero
v = M_zeros[:,:] = 0

# Reset our Matrix back to zero
M_zeros = M_zeros * 0

# Change v to hold numbers from 1 - 6 reshaped to (6,1)
v = np.arange(6).reshape(6,1)


# print for correctness
print(M_zeros)
print(v)

# Vector multiplication happens here...
M = M_zeros * v
print(M)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### np.where() <br>
<p>If statement within NDArrays that allows you to run conditionals on the entire array</p>

In [46]:
all_under_value = result_mul[np.where(result_mul <= 800)]
print(all_under_value)

[ 50 200 450 800]


#### Random Sampling <br>
<p>NumPy provides machinery to work with random numbers - something often needed in a broad spectrum of data science applications.</p>

In [47]:
# np.random.uniform()

# A single call generates a single random number between 0 and 1

print('Here is a random number: %s' % np.random.uniform())

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.uniform(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.uniform(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.uniform(0, 10, (3, 3)))

Here is a random number: 0.11214524110946722
Here is a random number between 0 and 1 Million: 636404.622274306
Here are 5 random numbers between 0 and 10: [6.77712743 1.66830492 1.17823327 6.47102323 7.14198479]
Here is a 3x3 matrix with numbers between 0 and 10: 
 [[3.18670574 1.71538914 8.31984267]
 [8.14270377 1.54421608 0.15047909]
 [7.51578071 6.47157884 8.88492088]]


## Working With CSV's

#### Imports

In [48]:
import csv
import numpy as np
from datetime import datetime

#### Reading a CSV

In [51]:
# Creating Function to open and read CSV data

def open_csv(filename, d = ','):
    # define an empty list to store our data
    data = []
    
    # Open our data file and read the contents inside
    with open(filename, encoding = 'utf-8') as mData:
        # use the csv.reader method to create a python list
        info = csv.reader(mData, delimiter = d)
        
        # Loop over info and append data to the empty list
        for row in info:
            data.append(row)
    return data

csv_data = open_csv('../files/boston_marathon2017_edited.csv')

print(csv_data[2])
    

['12/30/1899 12:30:27 AM', '12/30/1899 12:45:44 AM', '12/30/1899 1:01:15 AM', '12/30/1899 1:16:59 AM', '12/30/1899 1:33:01 AM', '12/30/1899 1:48:19 AM', '12/30/1899 2:03:14 AM', '12/30/1899 12:15:24 AM', '30', '17', '7798', 'USA', '7798', '', 'Portland', 'USA', '2', '2', '12/30/1899 1:04:35 AM', 'M', 'Rupp, Galen', '1', '12/30/1899 2:09:58 AM', '2', '12/30/1899 12:04:58 AM', 'OR']


#### Loading a CSV's Data 

In [53]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]



    # instead of loading csv normally, let's load it into a numpy array to calculate results on
def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data


bs2017 = load_data('../files/redsox_2017_hitting.txt')
# print(bs2017)

names = bs2017['Name']
print(names)

[b'Christian Vazquez' b'Mitch Moreland' b'Dustin Pedroia'
 b'Xander Bogaerts' b'Rafael Devers' b'Andrew Benintendi'
 b'Jackie Bradley Jr.' b'Mookie Betts' b'Hanley Ramirez' b'Sandy Leon'
 b'Chris Young' b'Deven Marrero' b'Eduardo Nunez' b'Brock Holt'
 b'Josh Rutledge' b'Pablo Sandoval' b'Sam Travis' b'Tzu-Wei Lin'
 b'Marco Hernandez' b'Rajai Davis' b'Steve Selsky' b'Blake Swihart'
 b"Chase d'Arnaud"]


#### Summing the top 5 hitters for HR's

In [57]:
# find the top 5 hr hitters

# Step 1: Get all HR data into a variable
# Step 2: Get all Player Names
# Step 3: Create new list for new_names (empty to start)
# Step 4: Decode the player names into regular strings
# Step 5: Grab all data and place inside of a zipped list
# Step 6: Sort values based on HR data

# Step 1
all_hr = bs2017['HR']

# Step 2
all_names = bs2017['Name']

# Step 3
new_names = []

# Step 4
for name in range(len(all_names)):
    new_names.append(all_names[name].decode('utf-8'))
# print(new_names)

# Step 5
zipped_values = list(zip(new_names, all_hr))
# print(zipped_values)

# Step 6
sorted_hr = sorted(zipped_values, key = lambda x: x[1], reverse = True)
print(sorted_hr[0:6])

# print(hr)


[('Mookie Betts', 24), ('Hanley Ramirez', 23), ('Mitch Moreland', 22), ('Andrew Benintendi', 20), ('Jackie Bradley Jr.', 17), ('Xander Bogaerts', 10)]


# Exercises To Complete.... <br>
<p>Given in separate file after completion of this file</p>